spring:
    datasource:
        username: hardcodedsecrets
        password: reallysecurepassword
        url: jdbc:mysql://myhost.com:3306/hardcodedsecrets
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop

